### ISSUE TITLE
Import classes with additional context

### ISSUE THREAD

**Issue by rweisleder** [TNG/ArchUnit#142]
### Context
I'm currently playing with ArchUnit and Spring. Consider this simple predicate to identify classes with Spring annotations:
```java
public static DescribedPredicate<CanBeAnnotated> haveSpringAnnotation(Class<? extends Annotation> annotationType) {
    return annotatedWith(annotationType).or(metaAnnotatedWith(annotationType)).as("are annotated with @" + annotationType.getSimpleName());
}
```
And this example rule to check that all Spring beans (having `@Component` somewhere) have a specific name:
```java
public static ArchRule BEAN_NAME_RULE = classes().that(haveSpringAnnotation(Component.class)).should().haveSimpleNameEndingWith("Bean");
```

What I learned is that `metaAnnotatedWith` only works reliably if I import the annotation class hierarchies.

This throws the expected violation:
```java
@Test
public void checkClassName() {
    JavaClasses classes = new ClassFileImporter().importClasses(Example.class);
    BEAN_NAME_RULE.check(classes);
}

@Component
private static class Example {}
```

This doesn't throw the expected violation:
```java
@Test
public void checkClassName() {
    JavaClasses classes = new ClassFileImporter().importClasses(Example.class);
    BEAN_NAME_RULE.check(classes);
}

@Service // @Service is meta-annotated with @Component
private static class Example {}
```

This throws the expected violation but also a violation that `@Service` doesn't have the expected simple name:
```java
@Test
public void checkClassName() {
    JavaClasses classes = new ClassFileImporter().importClasses(Example.class, Service.class);
    BEAN_NAME_RULE.check(classes);
}

@Service // @Service is meta-annotated with @Component
private static class Example {}
```

And of course: `resolveMissingDependenciesFromClassPath=true` ;)

### Problem
I'm looking for a solution to separate the classes that I want to check (Example.class) and the additional classes to make my custom rules work (Spring).

A simple solution would be:
```java
@Test
public void checkClassName() {
    Set<Location> myLocations = Locations.ofPackage("org.example"); // locations that I want to check
    Set<Location> additionalLocations = Locations.ofPackage("org.springframework"); // additional locations to import
    JavaClasses allClasses = new ClassFileImporter().importLocations(union(myLocations, additionalLocations));

    JavaClasses myClasses = allClasses.that(resideOutsideOfPackage("org.springframework.."));
    BEAN_NAME_RULE.check(myClasses);
}
```

Here I have to repeat the additional classes to exclude them from the checks. Also, my filtering with `resideOutsideOfPackage` ignores the concept that ClassFileImporter is based on `Location`. Currently, there seems to be no way to filter `JavaClasses` by `Location`.

How can we improve this?

### Thoughts about a solution
While thinking about this I came up with some ideas:
- Is there already a better way to do this?
- Extend ClassFileImporter to accept "additional context locations"
```java
ClassFileImporter cfi = new ClassFileImporter();
cfi.addImportContext(additionalLocations);
JavaClasses myClasses = cfi.importClasses(Example.class); // like myClasses above
```
- Bring together `JavaClass.getSource()` and the corresponding `Location` (if this is possible?) and add some predefined predicates
- …

**Comment by scranen** [comment]
Also bumping into this. It seems like the `ClassResolver` is not used to resolve annotation classes, which means that in most cases `isMetaAnnotatedWith` doesn't work as expected.

**Comment by codecholeric** [comment]
`ClassResolver` never resolves transitively. If your class is annotated with `@Service`, then `Service.class` will be resolved and imported, but transitive dependencies won't be.
I see the point here though, the ability to add more context that is not considered to be part of the classes under test seems valuable. There is a part of the creation processes where actually imported classes and additional classes resolved as dependencies are already treated separately (compare `com.tngtech.archunit.core.importer.ImportedClasses`), maybe it would be possible to integrate some additional context here.
Unfortunately my task pipeline is completely (over) full, so I won't be able to implement this within the next months. But I'd be happy if someone wants to jump in! Otherwise I'll try to get around to it once I have some spare time.

**Comment by KorSin** [comment]
Since #342 has been solved, meta annotations are now resolved and the above Example now works as intended, i.e., you do not need to import the `Service` class anymore.
Nevertheless, the proposal of having an additional context is interesting.

I would like to tackle this, but cannot think of an example now where this might be necessary. Any ideas, @codecholeric?

**Comment by codecholeric** [comment]
Hmm, that actually is a good question :thinking: I kind of think this is still valid though, in case you turn off resolution from the classpath. I would guess if you set

```
resolveMissingDependenciesFromClassPath=false
```

(as described in https://www.archunit.org/userguide/html/000_Index.html#_configuring_the_resolution_behavior), you would have the same problem again. And maybe then you would want to manually specify a couple of central infrastructure classes. But I'm not completely decided, as we could also mainly tackle the "resolve from classpath" case and make that really convenient by resolving everything automatically that would cause a problem here. What are your thoughts on this @rweisleder ? Every feature we don't need to maintain is happiness :wink: But every feature that really provides value is joy :joy:

**Comment by rweisleder** [comment]
Originally I had the idea for "import with additional context" because meta-annotations were not resolved satisfactorily at that time. This has been resolved with #342.

If a user sets `resolveMissingDependenciesFromClassPath=false`, then there are still other ways to achieve this, see my suggested workaround in the original post.

But currently I can't think of other use cases for this feature. 🤔 At least we already have an idea for a solution. Now we just need the right problem for it. 😂 

I am inclined to say that this issue can be closed.

**Comment by codecholeric** [comment]
Okay, that's fine with me :wink: I would not add the complexity, if we don't see a clear use case anymore that really brings value. If anybody stumbles over it in the future they can simply reopen this and we discuss it :slightly_smiling_face:

**Comment by codecholeric** [comment]
Sorry @KorSin, that exactly the issue you picked was outdated :joy: But feel free to pick any other issue or reach out, I'd be really happy to get more of your support! :sweat_smile:
